### PR TITLE
Update and rename gownifer_reborn.lic to alter.lic

### PR DESCRIPTION
**Pull request by ktig1**
Consolidated Gownifer_reborn with Corset, Shirt, and Pant variants, renamed to generic "alter"

### CODE REVIEW

**Review by mrhoribu — APPROVED** [review]
lgtm

**Comment by mrhoribu** [comment]
> lgtm

actually, something failed with the build due to a verification check after renaming. Looks like we may need to do something extra.

**Comment by mrhoribu** [comment]
@ondreian any idea how to fix verify_syntax check when a file gets deleted? Fairly certain the old one was renamed to alter.lic so the other one is acting like it's deleted and no longer valid.

```
$ bin/verify_syntax
             scripts/alter.lic
                                                  Syntax OK
   scripts/gownifer_reborn.lic
ruby: No such file or directory -- /home/travis/build/elanthia-online/scripts/scripts/gownifer_reborn.lic (LoadError)
The command "bin/verify_syntax" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by ondreian** [comment]
fixed this up and merged it in another working branch, thanks @ktig1 and @mrhoribu

**Pull request merged**
