### PR TITLE
Adds more potential boon prefixes

### PR DESCRIPTION
**Pull request by FarFigNewGut**
- combative
- drab
- unyielding
- enraged

are off the wiki and/or I've personally seen

- sickly-green

I've seen people with both "sickly green", and "sickly-green" listed for their existing bigshot excludes, I don't know which is correct so I added the dash but left the space version. The wiki has "sickly-green".

### CODE REVIEW

**Comment by sandersch** [comment]
The [boss creatures wiki page](https://gswiki.play.net/Boss_creatures) looks like it has "sickly green", not "sickly-green". I suspect that "sickly-green" is a typo that they've fixed as I checked my logs and I found a few boss creatures with "sickly-green" in early 2019, but lots of "sickly green" with examples as recent as last week in OTF: `sickly green greater construct`.

**Comment by athias** [comment]
Everything I've seen in all my logs references `sickly green` and not `sickly-green`.  There is not a single instance of sickly-green that I have found.
```GSF-Wukong/2020-08-07-8.log:You` are now targeting a sickly green kiramon defender.
GSF-Wukong/2020-08-07-8.log:You attempt to jab a sickly green kiramon defender!
GSF-Wukong/2020-08-07-8.log:You have decent positioning against a sickly green kiramon defender.```

**Comment by ondreian** [comment]
lgtm

**Review by mrhoribu — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
