### PR TITLE
Rename autoreact to autoreact.lic

### PR DESCRIPTION
**Pull request by AndreasWelch**
Noticed this was named as standard for other scripts.

### CODE REVIEW

**Comment by LeBigNasty** [comment]
This looks similar to both lines from bigshot and PSM3weapon.lic
Have you looked at those?

**Comment by AndreasWelch** [comment]
I have not.  I don't actually see the 2nd one you mention in the repository.  I wrote this right after reacts came out to be able to just run them automatically by autorunning this script.

This pull request is just to rename the file.

**Comment by LeBigNasty** [comment]
>;repo info psm3
--- Lich: repository active.
>

          file   size          last update       author   DLs   rating
--------------   ----   ------------------   ----------   ---   ------
psm3weapon.lic   0.4k   2021-08-10  9:54pm   Giantphang   180

**Comment by AndreasWelch** [comment]
Sorry for the confusion, I meant _this_ repository, not "the" repository.  Thank you for the merge.

**Pull request merged**
