### PR TITLE
Bigshot v3.8.7 Update

### PR DESCRIPTION
**Pull request by athias**
- Added overkill option for post-fried additional kills
  - Changed formatting to be more easily read and standardized
  - Added some tooltips
  - Added more clarified error messaging

### CODE REVIEW

**Comment by mrhoribu** [comment]
Hard to see the actual changes that were done due to formatting cleanup via diff view. But so far I've run it a few times and don't see any issues so far.

**Comment by athias** [comment]
Yeah, I kind of wish I didn't do all the formatting changes at the same time.  Git differences really aren't very good at dealing with that.
I've run it through several tests and worked out all the bugs I saw - So, this is the finished product.

**Comment by ondreian** [comment]
Just FYI, you can clean up a lot of formatting diffs by ignoring whitespace: 
ignore_white_space

[link to diff without whitespace changes showing](https://github.com/elanthia-online/scripts/pull/219/files?diff=split&w=1)

**Comment by mrhoribu** [comment]
Oh very nice, did not know git had that option. Thanks.

**Pull request merged**
