### PR TITLE
The selfcast check in bigshot was ugly

### PR DESCRIPTION
**Pull request by slitherrr**
Unnecessary cast to string, unecessary regex, massive one-liner, etc. Also includes Nidal's fix from [here](https://discord.com/channels/226045346399256576/387286877327065108/794212531518308413) but that could use a double-check for accuracy since it's actual functionality.

I haven't tested this.

### CODE REVIEW

**Comment by slitherrr** [comment]
Someone's editor does not have "delete extra whitespace at end of line" turned on. To git rid of extraneous crap, use this option:

image

**Comment by slitherrr** [comment]
I also changed all `if !foo A else B` to `if foo B else A`

**Comment by athias** [comment]
I recommend we leave this open for the time being

There are significant changes being made, and I can incorporate this into the updated version.  Should be good to release it later today

**Review by athias — CHANGES_REQUESTED** [review]
Please leave this PR open to have changes incorporated into upcoming v4 of bigshot. Will be followed up with closure.

**Comment by athias** [comment]
Changes from this PR were rolled into PR #375 for the Bigshot 4 updates

**Pull request closed without merging**
