### PR TITLE
 Add interaction monitor options to specify expressions

### PR DESCRIPTION
**Pull request by ImperArx**
I got tired of having the Dreavening line "There is nothing to report at this time, chief." cause an interaction window to pop up.  When I went to add something to the interaction monitor to ignore that, I realized that both the expressions to watch for and the expressions to ignore should be configurable, so I wrote this.

I've moved the options for the interaction monitor to their own settings tab named "Monitoring", and created text areas there for easy editing of multiple expressions.  The joined expressions are split for the text areas but stored as single string.

new_bigshot_monitor_options

I also did some drying up of the code that creates the settings window to make adding a window easier, and to make the code a little more compliant with the general Ruby community style.

### CODE REVIEW

**Comment by mrhoribu** [comment]
Looks good, have you tested it with GTK2 or GTK3? I updated the version # and added a 1617 zealot change_stance fix that I was needing to do as well.

**Comment by mrhoribu** [comment]
So went to test this on my build (Ruby 2.7.1 and GTK2) and definitely having issues. It was the first time I had ran a v4 bigshot branch as I was previously still using v3.92 myself. Immediately it closes out of the game session. I then downloaded the latest version from the repo (v4.1.1) and it opens fine. Then tried rerunning your code again and it opens ok now as well.

I had another person who's on GTK3 run the code and there are fatal issues with it, log below:

```

>;bigshot2 setup
--- Lich: bigshot2 active.
error in Gtk.queue: <Gtk::Container#add>: the 0th argument must not nil: <widget>
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:514:in `block in define_method'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gtk3-3.4.3/lib/gtk3/container.rb:23:in `add'
	bigshot2:2738:in `block in setup'
	C:/google_drive/Gemstone/Lich-GTK3/lich.rbw:714:in `block in queue'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:598:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:598:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:103:in `block in define_singleton_method'
error in Gtk.queue: <Gtk::Table#attach>: the 3rd argument must not nil: <top_attach>
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:600:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:514:in `block in define_method'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gtk3-3.4.3/lib/gtk3/table.rb:36:in `attach'
	bigshot2:3036:in `block in setup'
	C:/google_drive/Gemstone/Lich-GTK3/lich.rbw:714:in `block in queue'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:598:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:598:in `invoke'
	C:/BetaGTK3-Ruby4Lich/lib/ruby/gems/2.6.0/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:103:in `block in define_singleton_method'
>
```

@ImperArx can you confirm if you tested on both GTK2 and GTK3?

**Comment by athias** [comment]
So, I reviewed it, and found that the get_VBOX proc being deleted was the source of the issues.  This allows one of the main compatibility differences between GTK2 and GTK3.  Restoring it allowed me to verify it works in GTK3.

I also added in the changelog - which should always be added especially when making large changes.  Smaller changes are always recommended

**Comment by mrhoribu** [comment]
Verified it's working on GTK2 as well after reverting and blowing out my bigshot settings to test upgrade from v3 to v4 of bigshot branch.

**Comment by ImperArx** [comment]
Thanks for fixing up the issue with GTK3, I hadn't gone back and tested that properly.  Also glad someone remembered to add a version bump and change log for this.  Knew something was going to slip my mind when I submitted this.

**Pull request merged**
