### PR TITLE
Create 34_kf_herbs.rb

### PR DESCRIPTION
**Pull request by mrhoribu**
add herbs from KF.

### CODE REVIEW

**Comment by mrhoribu** [comment]
tkaro root likely can be removed as it's not really a herb and is more magical in nature to turn off now obsolete ESP.

**Comment by ondreian** [comment]
lgtm, but are we removing the tkaro root?

**Comment by sandersch** [comment]
imho even if the current effect of tkaro root isn't useful, it otherwise behaves like other herbs as a forageable/bundleable alchemy ingredient etc so unless it is causing pain or toil somewhere I would keep it

**Comment by mrhoribu** [comment]
I'm in agreement with @sandersch and we can leave it in for now and remove it if we need to later.

**Pull request merged**
