### PR TITLE
Removing 2.0.2 SLoot UI / LIC until it is prod ready

### PR DESCRIPTION
**Pull request by OSXLich-Doug**
Working to position GTK3 sloot until SLoot 2.0.2 is repaired (sells from all containers, does not sell excluded items, does not sell excluded scrolls).

This PR removes SLoot lic and ui to craeta space for GTK3 sloot as 'sloot'.

### CODE REVIEW

**Comment by ondreian** [comment]
You should not just delete these files, someone can name squat on `;repo` if you do.

**Comment by OSXLich-Doug** [comment]
@ondreian - Wasn't going to just delete.  Also pushed a PR that adds gtk3 sloot per discussion.  I presume it will be ok to delete and add.  Is there a better way, though, before I push the button?

**Comment by ondreian** [comment]
you shouldn't need to delete and add if you have the latest changes from master before you fork, just commit the new sloot stuff and it should be fine then

**Comment by OSXLich-Doug** [comment]
Ok, I'll close the existing and try again to meet that requirement.  Thanks!

**Comment by OSXLich-Doug** [comment]
Closing after above exchange, will recast PR as recommended above.

**Pull request closed without merging**
